### ISSUE TITLE
Little typo

### ISSUE THREAD

**Issue by andrewrogow** [AlexandarVysotskiy/AVysotskiy#1]
https://github.com/AlexandarVysotskiy/AVysotskiy/blob/0025fb873aaf703c60cfac7ae6b9d9837df5b4fb/chapter_001/src/main/java/ru/job4j/Calculate.java#L18

Probably you mean `"I will not write: Hello World"`

**Comment by AlexandarVysotskiy** [comment]
Thank you, I wrote this when I just started learning English.
